### ISSUE TITLE
custom data

### ISSUE THREAD

**Issue by yunmengmengyun** [Jiaqi-zhang/HoughLaneNet#1]
Dear author,

Thanks for you job. 
May I ask if I want to run my own images and videos with your models, which configurations in the code I need to change to get the best result?  e.g. original img sizes.
Because I found the performance on my own images was very poor. 

Thanks in advance!

If possible, is there a script which can just read an image or a video and output the resulting image or video?

**Comment by Jiaqi-zhang** [comment]
Is your dataset exceedingly complex, even surpassing that of the CULane dataset? The model performs accurately on highways, as demonstrated on the TuSimple dataset, but its performance deteriorates on urban roads like those in the CULane dataset. Data preprocessing is already incorporated in the code, employing commonly used techniques such as random cropping and image flipping, without any special handling.

Additionally, you can visualize the distribution of Hough points in your dataset images to observe any significant clustering patterns. If most images contain four lane lines, there will be four clustered regions in the Hough space.

**Comment by yunmengmengyun** [comment]
Here is my input image and the output by using commend "CUDA_VISIBLE_DEVICES=0 bash tools/single_disp_culane.sh configs/lane/culane_res_large.py ./pretrained_weights/culane/res_large/culane_res_large_epoch.pth  --data-dir ./demo/input/ --show-dir ./demo/output/"

I changed the name of my the input image to driver_37_30frame_05181432_0203.MP4_01860 which is same with the name of a image in demo. I also resized the input image to (1640, 590).   The input image is also a highway image, not very complex.  but the lane detection result is very poor. 

So, are you able to get a better result on my image? or is there any other configurations need to be changed to get a better result?

Thank you in advance!!!!!!!!!!!!!!

**Comment by Jiaqi-zhang** [comment]
The configuration file contains the following settings that can be adjusted:

- `hough_point_radius = 3`
- `hough_point_ratio = 1.0`
- `threshold = 0.135`

Particularly, the final parameter, `threshold`, is highly sensitive to the results.
Additionally, you may consider experimenting with the model trained on the TuSimple dataset.

**Comment by yunmengmengyun** [comment]
Thanks, I will try!

**Comment by yunmengmengyun** [comment]
Emm, I tried tusimple_res_large.py. but the result is still bad. If you happen to get a better result, please let me know. 
Thanks a lot!

![driver_37_30frame_05181432_0203 MP4_01860-tusimple](https://github.com/user-attachments/assets/668bb871-9eb3-4af7-a28a-774e3092bda1)

**Comment by yunmengmengyun** [comment]
by the way, I changed the hough_point_radius = 3, hough_point_ratio = 1.0, threshold = 0.135 in the tusimple_res_large.py or culane_res_large.py, but seems doesn't work better.

**Comment by yunmengmengyun** [comment]
> Emm, I tried tusimple_res_large.py. but the result is still bad. If you happen to get a better result, please let me know. Thanks a lot!
> 
> ![driver_37_30frame_05181432_0203 MP4_01860-tusimple](https://private-user-images.githubusercontent.com/44886639/381969153-668bb871-9eb3-4af7-a28a-774e3092bda1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODI2NTgsIm5iZiI6MTczMDM4MjM1OCwicGF0aCI6Ii80NDg4NjYzOS8zODE5NjkxNTMtNjY4YmI4NzEtOWViMy00YWY3LWEyOGEtNzc0ZTMwOTJiZGExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDEzNDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZWZhOWJmM2RkZDYzMzE0ZWQ2OTZkYjkzMDJiM2IwYjUwZTFlODQ2YWU1YmM4MmQ1ZTE4Mzk1ZDUyMjA0YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JQP7qaHs2tT-mKfKdhxcz7mWyPN0O1YzyzfT5OKBWDU)

especially the broken lines in the middle was not detected!

**Comment by Jiaqi-zhang** [comment]
Consider adjusting the parameter threshold to 0.1. The smaller this value is, the more lanes will be detected.
